 version: '3'
 services:

  db:
	image: mongo:latest
	container_name: mongo
	ports:
	  - 27017:27017
    command:  bash -c "mongo
             && show databases
             && use cinema
             && exit"
	networks:
      - backend
	  
  server:
	build: ./server
	container_name: server
	ports:
	  - 3000:3000
	networks:
    - backend
		
  client :
	build: ./client
	container_name: client
	ports:
	  - 8000:8000
	networks:
    - frontend
	
 networks:
   frontend:
   backend:
	
	  
	  
	  