version: "3.9"
services:
  web-server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
  Web-client:
    build: ./client
    container_name: client
    ports: 
      - "8000:8000"
  db:
    image: "mongo:latest"
    container_name: mongo